apps/fiscalizacion/urls.py
from django.conf.urls import patterns, url
from django.views.generic import TemplateView

from apps.actas.views import FiscalizacionView as fiscalizacion
from apps.fiscalizacion.views import Pdf
from apps.fiscalizacion.views import concluir_fiscalizacion_json
from apps.fiscalizacion.views import guardar_acta_reparo_json
from apps.fiscalizacion.views import guardar_nueva_acta_reparo_json
from apps.fiscalizacion.views import obtener_acta_reparo_json
from apps.fiscalizacion.views import registrar_observaciones_json


urlpatterns = patterns('',
                       url(r'^$',
                           fiscalizacion.FiscalizacionListView.as_view(),
                           name='funcionario_fiscalizaciones'),

                       url(r'^(?P<pk>\d+)/$',
                           fiscalizacion.FiscalizacionDetailView.as_view(),
                           name='funcionario_detalle_fiscalizacion'),

                       url(r'^solicitud/de/aprobacion/1/$',
                           TemplateView.as_view(template_name='fiscalizacion/funcionario/solicitud_aprobacion.html'),
                           name='funcionario_solicitud_de_aprobacion_fiscalizacion'),

                       url(r'^seleccionar/candidato/$',
                           TemplateView.as_view(template_name='fiscalizacion/funcionario/candidatos.html'),
                           name='funcionario_seleccionar_candidato_fiscalizacion'),

                       url(r'^nueva/$',
                           TemplateView.as_view(template_name='fiscalizacion/funcionario/nueva.html'),
                           name='funcionario_nueva_fiscalizacion'),

                       url(r'^gerente/$',
                           TemplateView.as_view(template_name='fiscalizacion/funcionario/fiscalizacion_gerente.html'),
                           name='funcionario_fiscalizacion_gerente'),

                       url(r'^edicion/$',
                           TemplateView.as_view(template_name='fiscalizacion/funcionario/edicion_fiscalizacion.html'),
                           name='funcionario_edicion_fiscalizacion'),

                       # utilities views
                       url(r'^get/codigo/ajax/$',
                           fiscalizacion.FiscalizacionGetCodigoView.as_view(),
                           name='ajax_codigo_fiscalizacion'),

                       url(r'^get/data/ajax/$',
                           fiscalizacion.FiscalizacionGetDataView.as_view(),
                           name='ajax_data_fiscalizacion'),

                       url(r'^eliminar/acta/(?P<pk>\d+)/para/fiscalizacion/(?P<pk_fiscalizacion>\d+)/$',
                           fiscalizacion.FiscalizacionEliminarActaView.as_view(),
                           name='eliminar_nueva_acta_fiscalizacion'),

                       url(r'^nueva/acta/para/fiscalizacion/(?P<pk>\d+)/$',
                           fiscalizacion.FiscalizacionCrearActaView.as_view(),
                           name='crear_nueva_acta_fiscalizacion'),

                       url(r'^editar/acta/para/fiscalizacion/(?P<pk>\d+)/$',
                           fiscalizacion.FiscalizacionEditarActaView.as_view(),
                           name='editar_nueva_acta_fiscalizacion'),

                       url(r'^anular/acta/providencia/para/verificacion/(?P<pk>\d+)/$',
                           fiscalizacion.AnularActaProvidencia.as_view(),
                           name='anular_providencia_acta_fiscalizacion'),
                       # pdf
                       url(r'^pdf/(.+)/$',
                           Pdf.as_view(),
                           name='fiscalizacion_pdf'),

                       url(r'^lista/actas/para/aprobar/$',
                           fiscalizacion.ActaListView.as_view(),
                           name='actas_lista_para_aprobar'),

                       # ajax
                       url(r'^concluir.json$',
                           concluir_fiscalizacion_json,
                           name='fiscalizacion_concluir_json'),

                       url(r'^guardar_acta_reparo.json$',
                           guardar_acta_reparo_json,
                           name='fiscalizacion_guardar_acta_reparo_json'),

                       url(r'^guardar_nueva_acta_reparo.json$',
                           guardar_nueva_acta_reparo_json,
                           name='fiscalizacion_guardar_nueva_acta_reparo_json'),

                       url(r'^obtener_acta_reparo.json$',
                           obtener_acta_reparo_json,
                           name='fiscalizacion_obtener_acta_reparo_json'),

                       url(r'^registrar_observaciones.json$',
                           registrar_observaciones_json,
                           name='fiscalizacion_registrar_observaciones_json'),

                       url(r'^actas/solicitar-aprobacion.json$',
                           fiscalizacion.solicitar_aprobacion_json,
                           name='fiscalizacion_solicitar_aprobacion_json'),
)

mintur/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView, RedirectView
from django.core.urlresolvers import reverse_lazy
from django.contrib import admin
from settings import MEDIA_URL
from utils import vzla as restVenezuela
from utils import validaciones
from apps.cuentas.views import DetectarUsuarioView
from views import files_view

admin.autodiscover()

urlpatterns = patterns('',

  url(r'^admin/', include(admin.site.urls)),

  # App para la creacion de cuentas y auth
  url(r'^cuentas/', include('apps.cuentas.urls')),

  # App que maneja todo lo referente al registro de PST
  url(r'^registro/', include('registro.urls')),

  # App que maneja todo lo referente a RTN
  url(r'^rtn/', include('apps.rtn.urls')),

  # App que maneja todo lo referente a Licencias
  url(r'^licencias/', include('apps.licencias.urls')),

  # App que maneja todo lo referente a Factibilidad
  url(r'^factibilidad/', include('apps.factibilidad.urls')),

  # App que maneja todo lo referente a Declaraciones
  url(r'^declaraciones/', include('declaraciones.urls')),

  # App que maneja todo lo referente a Verificacion
  url(r'^verificacion/', include('apps.verificacion.urls')),

  # App que maneja todo lo referente a Fiscalizacion
  url(r'^fiscalizacion/', include('apps.fiscalizacion.urls')),

  # App que maneja todo lo referente a Pagos
  url(r'^pagos/', include('apps.pagos.urls')),

  # App que maneja todo lo referente a Metas
  url(r'^metas/', include('apps.metas.urls')),

  # App que maneja todo lo referente a Metas
  url(r'^reportes/', include('apps.reportes.urls')),

  # App que maneja todo lo referente a Resoluciones
  url(r'^resoluciones/', include('apps.resoluciones.urls')),

  # App que maneja todo lo referente a las Solicitudes
  url(r'^inteligencia_tributaria/', include('apps.inteligencia_tributaria.urls')),

  # App que maneja todo lo referente a la configuracion
  url(r'^configuracion/', include('apps.configuracion.urls')),

  # Vista que se encarga de enviar el usuario a la vista que le corresponde
  url(r'^$',
     DetectarUsuarioView.as_view(),
     name='cuentas_detectar_usuario'),

  url(r'^funcionario/$',
     RedirectView.as_view(url=reverse_lazy('registro_funcionario_solicitudes'))),


  url(r'^404$',
     TemplateView.as_view(template_name='404.html'),
     name='404'),

  url(r'^500$',
     TemplateView.as_view(template_name='500.html'),
     name='500'),

  url(r'^municipios/(?P<pk>\d+)/$', restVenezuela.municipios_json,
    name='municipios_json'),

  url(r'^parroquias/(?P<pk>\d+)/$', restVenezuela.parroquias_json,
    name='parroquias_json'),

  url(r'^' + MEDIA_URL[1:] + '(?P<fpath>.*)$', files_view, name="files_view"),

  url(r'^validar_rif$', validaciones.ValidarUnicoRif.as_view(), name='validar_rif'),

  url(r'^validar_cedula$', validaciones.ValidarUnicoDocumento.as_view(), name='validar_cedula'),
  #reportes

  # Modulo de Categorizacion
  url(r'^categorizacion/', include('apps.categorizacion.urls'))

  )

apps/actas/models.py
# coding=utf-8

from django.db import models

from utils.gluon.storage import Storage
from registro.models import Pst
from apps.fiscalizacion.models import Fiscalizacion
from apps.verificacion.models import Verificacion
from apps.cuentas.models import MinturUser

NO_NOTIFICADA = 1
NOTIFICADA = 2
CONCLUIDA = 3
ANULADA = 4
APROBACION_SOLICITADA = 5
APROBADA = 6

ESTATUS_ACTA = (
    (NO_NOTIFICADA, u'No notificada'),
    (NOTIFICADA, u'Notificada'),
    (CONCLUIDA, u'Concluida'),
    (ANULADA, u'Anulada'),
    (APROBACION_SOLICITADA, u'Aprobación solicitada'),
    (APROBADA, u'Aprobada'),
)


class TipoActa(models.Model):
    nombre = models.CharField(max_length=250, blank=False, null=False)
    codigo_documento = models.CharField(max_length=10, blank=False, null=False, default="")

    @classmethod
    def create(cls, data):
        """
        Crea una nueva instancia del objeto TipoActa a partir
        de la información suministrada.
        Parametros:
        Storage data debe contener
        - nombre (str): Nombre del tipo de acta
        """

        if isinstance(data, Storage):
            obj = cls()
            obj.nombre = data.nombre
            return obj
        else:
            raise NameError('Error de Tipo. Los parametros enviados no son correctos')


class ActaDocumentos(models.Model):
    codigo = models.CharField(max_length=250, blank=True, null=True, unique=True)
    tipo = models.ForeignKey(TipoActa)
    providencia = models.ForeignKey('self', blank=True, null=True)
    estatus = models.IntegerField(choices=ESTATUS_ACTA, blank=True, null=True)
    pst = models.ForeignKey(Pst, related_name='pst_actas_v_f', blank=True, null=True)
    verificacion = models.ForeignKey(Verificacion, null=True, blank=True, default=None)
    fiscalizacion = models.ForeignKey(Fiscalizacion, null=True, blank=True, default=None)
    fecha_generacion = models.DateTimeField(auto_now_add=True)
    fecha_notificacion = models.DateField(blank=True, null=True)
    observaciones = models.TextField(max_length=250, null=True, blank=True)
    hallazgos_materia = models.TextField(max_length=250, null=True, blank=True)
    hallazgos_condicion = models.TextField(max_length=250, null=True, blank=True)
    hallazgos_criterio = models.TextField(max_length=250, null=True, blank=True)
    hallazgos_efecto = models.TextField(max_length=250, null=True, blank=True)
    hallazgos_evidencia = models.TextField(max_length=250, null=True, blank=True)

    @classmethod
    def create(cls, data):
        """
        Crea una nueva instancia del objeto Acta a partir
        de la información suministrada.
        Parametros:
        Storage data debe contener
        - codigo (str): Nombre del tipo de acta
        - tipo (object): Tipo de acta
        - providencia (object): Acta padre del modelo
        - estatus (int): Estado del acta
        - pst (object): Nombre del tipo de acta
        - verificacion (object): Verificación asociada al acta
        - fiscalizacion (object): Fiscalización asociada al acta
        - fecha_generacion (date): Fecha en la que se genera el acta
        - fecha_notificacion (date): Fecha en la que se genera la notificacion
        - observaciones (str): Observaciones del acta
        - hallazgos_materia (str): Materia
        - hallazgos_condicion (str): Condicion
        - hallazgos_criterio (str): Criterio
        - hallazgos_efecto (str): Efecto
        - hallazgos_evidencia (str): Evidencia
        """

        if isinstance(data, Storage):
            obj = cls()
            obj.codigo = data.codigo
            obj.tipo = data.tipo
            obj.providencia = data.providencia
            obj.estatus = data.estatus
            obj.pst = data.pst
            obj.verificacion = data.verificacion
            obj.fiscalizacion = data.fiscalizacion
            obj.fecha_generacion = data.fecha_generacion
            obj.fecha_notificacion = data.fecha_notificacion
            obj.observaciones = data.observaciones
            obj.justificacion_cambio_de_estatus = data.justificacion_cambio_de_estatus
            obj.hallazgos_materia = data.hallazgos_materia
            obj.hallazgos_condicion = data.hallazgos_condicion
            obj.hallazgos_criterio = data.hallazgos_criterio
            obj.hallazgos_efecto = data.hallazgos_efecto
            obj.hallazgos_evidencia = data.hallazgos_evidencia
            return obj
        else:
            raise NameError('Error de Tipo. Los parametros enviados no son correctos')

    def mostrar_boton_solicitud(self):
        return (
            self.tipo.nombre == u'Acta de reparo' and self.estatus == 1
        )


class ActaReparoAtributos(models.Model):
    periodo = models.CharField(max_length=250, blank=True, null=True, unique=True)
    ingresos_brutos = models.FloatField()
    calculo_segun_fiscalizacion = models.FloatField()
    monto_pagado_segun_declaracion = models.FloatField()
    diferencia_por_pagar = models.FloatField()
    acta = models.ForeignKey(ActaDocumentos)

    @classmethod
    def create(cls, data):
        """
        Crea una nueva instancia del objeto Acta a partir
        de la información suministrada.
        Parametros:
        Storage data debe contener
        - periodo (str):
        - ingresos_brutos (float):
        - calculo_segun_fiscalizacion (float):
        - monto_pagado_segun_declaracion (float):
        - diferencia_por_pagar (float):
        - acta (Object):
        """

        if isinstance(data, Storage):
            obj = cls()
            obj.periodo = data.periodo
            obj.ingresos_brutos = data.ingresos_brutos
            obj.calculo_segun_fiscalizacion = data.calculo_segun_fiscalizacion
            obj.monto_pagado_segun_declaracion = data.monto_pagado_segun_declaracion
            obj.diferencia_por_pagar = data.diferencia_por_pagar
            obj.acta = data.acta
            return obj
        else:
            raise NameError('Error de Tipo. Los parametros enviados no son correctos')


class Requisito(models.Model):
    requisito = models.TextField(max_length=250, null=True, blank=True)

    @classmethod
    def create(cls, data):
        """
        Crea una nueva instancia del objeto Requisito a partir
        de la información suministrada.
        Parametros:
        Storage data debe contener
        - requisito (str): Requisito a guardar
        """

        if isinstance(data, Storage):
            obj = cls()
            obj.requisito = data.requisito
            return obj
        else:
            raise NameError('Error de Tipo. Los parametros enviados no son correctos')

    def __unicode__(self):
        return self.requisito


class ActaRequisito(models.Model):
    acta = models.ForeignKey(ActaDocumentos, related_name='actas_v_f')
    requisito = models.ForeignKey(Requisito)
    entrego = models.BooleanField(default=False)

    @classmethod
    def create(cls, data):
        """
        Crea una nueva instancia del objeto ActaRequisito a partir
        de la información suministrada.
        Parametros:
        Storage data debe contener
        - acta (str): Referencia al acta
        - requisito (str): Requisito a guardar
        - entrego (str): Entregó o no el requisito
        """

        if isinstance(data, Storage):
            obj = cls()
            obj.acta = data.acta
            obj.requisito = data.requisito
            obj.entrego = data.entrego
            return obj
        else:
            raise NameError('Error de Tipo. Los parametros enviados no son correctos')


class ActaLogCambiarStatus(models.Model):
    acta = models.ForeignKey(ActaDocumentos, related_name='actas_log_c_s')
    estatus = models.IntegerField(choices=ESTATUS_ACTA)
    fecha_generacion = models.DateTimeField(auto_now_add=True)
    fecha_notificacion = models.DateField(blank=True, null=True)
    justificacion_cambio_de_estatus = models.TextField(max_length=250, null=True, blank=True)
    funcionario = models.ForeignKey(MinturUser)
    pst = models.ForeignKey(Pst)

    @classmethod
    def create(cls, data):
        """
        Crea una nueva instancia del objeto ActaRequisito a partir
        de la información suministrada.
        Parametros:
        Storage data debe contener
        - acta (str): Referencia al acta
        - requisito (str): Requisito a guardar
        - entrego (str): Entregó o no el requisito
        """

        if isinstance(data, Storage):
            obj = cls()
            obj.acta = data.acta
            obj.estatus = data.estatus
            obj.fecha_generacion = data.fecha_generacion
            obj.fecha_notificacion = data.fecha_notificacion
            obj.justificacion_cambio_de_estatus = data.justificacion_cambio_de_estatus
            obj.funcionario = data.funcionario
            obj.pst = data.pst
            return obj
        else:
            raise NameError('Error de Tipo. Los parametros enviados no son correctos')

templates/fiscalizacion/actas/solicitudes.html
{% extends "base_funcionario.html" %}
{% load filtros_solicitudes %}
{% load filtros_datos %}
{% block main_content %}
    <!-- Right side column. Contains the navbar and content of the page -->
    <aside class="right-side">
        <section class="content-header">
            <h1>Aprobación de Actas
                <small>Panel de control</small>
            </h1>
            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-edit"></i> Aprobación de Actas </a></li>
                <li class="active">Panel de control</li>
            </ol>
        </section>
        <!-- Main content -->
        <section class="content">
            <div class="box box-danger">
                <div class="box-body">
                    <div class="body" id="persona-juridica">
                        <div class="row">
                            <div class="col-xs-6 col-xs-offset-6">
                                <label>RIF</label><br>

                                <div class="input-group">
                                    <input type="text" class="form-control rif-mask">

                                    <div class="input-group-addon">
                                        <i class="fa fa-search"></i>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <br>

                        <div class="row">
                            <div class="col-xs-12">
                                <table class="table table-striped table-partner table-hover">
                                    <thead>
                                    <tr>
                                        <th>RIF</th>
                                        <th>Razón social</th>
                                        <th>Tipo de PST</th>
                                        <th>Estatus</th>
                                        <th>Opciones</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for solicitud in solicitudes %}
                                        <tr>
                                            <td>{{ solicitud.pst.rif }}</td>
                                            <td>{{ solicitud.pst.razon_social }}</td>
                                            <td>{{ solicitud.pst|get_tipo_pst }}</td>
                                            <td>
                                                <small class="label label-warning">{{ solicitud.get_estatus_display }}</small>
                                            </td>
                                            <td>
                                                <a href="{% url 'funcionario_detalle_fiscalizacion' solicitud.id %}"
                                                   class="btn btn-info ">
                                                    <i class="fa fa-search icon-white"></i>
                                                </a>
                                            </td>
                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="modal fade" id="nueva-solicitud" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
                 aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                            <h4 class="modal-title" id="myModalLabel">Nueva solicitud</h4>
                        </div>
                        <div class="modal-body" id="funcionario">
                            <div class="row">
                                <div class="col-xs-6 text-right">
                                    <label>Tipo de verificación:</label>
                                </div>
                                <div class="col-xs-6">
                                    <select class="select">
                                        <option>Individual</option>
                                        <option>Grupal</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <div class="row">
                                <div class="col-xs-6">
                                    <a href="{% url 'funcionario_verificaciones_solicitudes' %}"
                                       class="btn btn-primary btn-block btn-flat">Aceptar</a>
                                </div>
                                <div class="col-xs-6">
                                    <a href="#" class="btn btn-danger btn-block btn-flat"
                                       data-dismiss="modal">Cancelar</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </section>

    </aside>
{% endblock %}